locustfile = ../obsload.py
# headless is required to run
headless = true
# replace with actual bucket
bucket = benchmark
loglevel = DEBUG
run-time = 15m

# Convenient to keep a list of lines here when comparing different endpoints
s3-endpoint = https://s3server
#s3-endpoint = https://s3altserver

# Put common overrides here when varying something else in config files
# (like a file spec)
#cadence = 42-90
#process-delay = 50-60
